version : "3"
services: 
  app: 
    build: ./nodemon
    ports:
     - 7000:7000
    volumes:
     - ./:/app
    links:
     - mysql_database   
  mysql_database: 
    image: mysql
    volumes:
     - ./mysql/data:/var/lib/mysql
    environment:
     - MYSQL_DATABASE=thailand_province
     - MYSQL_USER=thailand_province
     - MYSQL_PASSWORD=th_province
     - MYSQL_ROOT_PASSWORD=root
    ports: 
     - 3306:3306
  